
<script>


    /* 
    continue
    -반복문의 처음으로 돌아감
    */

    for (var k =0; k<5; k++) {
        if (k===2 || k===3){
            continue;
        };
        console.log(k);
    };
    /*실행결과 : 0    1    4
        k가 2 또는 3이면 continue를 만나서
        반복문의 처음으로 돌아가고 console.log(k)를 실행하지 않는다. 
    Continue는 어디로 가냐가 중요하다!*/

    // switch문

    var exp = 1;
    switch(exp){
        case 1:
        console.log(100);
        case 2:
        console.log(200);
    };

    /*실행결과 : 100        200
        switch(exp)에서 exp를 평가하여 값을 구하고 구한 값에 일치하는 case문을 수행
        ***주의 ****
        case1 아래의 모든 문장을 수행하므로 100과 200이 출력됨
        이를 방지하려면 break를 작성해야함 */

    /* switch문인데 일치하는 case가 없어서 default를 수행할때 */

    var exp = 7, value;
    switch(exp){
        case 1:
        value = 100;
        default:
        value = 700;
        case 2:
        value = 200;  
    };
    console.log(value);

    /* 실행결과 : 200
    default값은 700인데 왜 200이 실행됨?
    break를 넣지 않았기 때문에 default값으로 처음에 700할당 되었다가
    그 뒤에서 value가 200으로 수정되어 할당됨!
    따라서 출력값은 200이 됨.*/


    /* switch문인데 OR(||) 형태로 나올경우 */
    var exp = 3;
    switch(exp){
        case 2:
        case 3:
            console.log(100);
    };

    /* 실행결과 : 100
    exp가 2 또는 3이면 case를 수행 */



    /* try-catch
    -형태: 
        try catch
        try finally
        try catch fianlly
    -try문에서 예외 발생을 인식
    -예외가 발생하면 catch블록 실행
    -finally블록은 예외 발생과 관계없이 실행
    */

    var value;
    try {
        value = ball;
    } catch(error) {
        console.log("catch 실행");
    };

    /* 실행결과 : catch 실행
    try블록에서 vall을 value에 할당할 때 ball 변수가 선언이 되어있지 않으므로 에러 발생
    에러가 발생하면 catch(error)블록 실행
    에러가 발생할 가능성이 있으면 반드시 try-catch를 사용해야 함.*/

    //finally블록은 에러가 나든 에러가 나지 않든 무조건 실행

    var sports;
    try {
        sports = ball;
    } catch (error) {
        console.log("catch 실행");
    } finally {
        console.log("finally 실행");
    };

    /* 실행결과 : catch 실행            finally실행
        try에서 에러가 발생하면 catch()블록을 실행한 후 finally 블록 실행
        try에서 에러가 발생하지 않아도 finally불록 실행 */

    /* throw
    -형태:
        throw 표현식;
    -명시적으로 예외를 발생시킴
    -예외가 발생하면 catch실행
    */

    try {
        throw "예외 발생시킴";
        var sports = "스포츠";
    } catch(error){
        console.log(error);
        console.log(sports);
    };

    /* 실행결과 : "예외 발생시킴"           undefined
    throw를 만나면 에러가 발생한다
    throw뒤의 문자열을 error로 설정하여
    error를 찍는다.
    
    throw아래 부분은 실행되지 않기 떄문에 console.log(sports)는 undefined가 뜬다
    */

    /* throw 표현식을 오브젝트 형태로 작성가능 */

    try {
        throw {
            msg: "예외 발생시킴",
            bigo: "임의의 이름 사용"
        };
    } catch(error){
        console.log(error.msg);
        console.log(error.bigo);
    };

    /* 실행결과 : 예외 발생시킴             임의의 이름 사용
    throw표현식에 오브젝트를 작성한 형태
    catch(error)의 error에 Error 오브젝트가 설정됨 */


    /* Error 오브젝트를 생성하여 사용 (Error는 자바스크립트에서 제공하는 오브젝트)
    앞의 것과 다른점은 오브젝트를 만들어 사용한다는 차이점만 있음!*/

    try {
        throw new Error("예외 발생시킴");
    } catch(error){
        console.log(error.message);
    };

    /* throw표현식에 Error오브젝트 작성
    Error()파라미터에 메시지 작성
    오브젝트의 message에 메시지가 자동 설정됨
    
    catch(error)의 error에 Error오브젝트가 설정됨
    error.message로 작성한 메시지 사용
    */


    /* strinct 모드
    "use strict"
    -작성한 위치부터 적용
    -엄격하게 자바스크립트 문법 사용 선언
    */

    /*함수 (function)
    -특정 기능을 처리하는 자바 스크립트 코드 묶음
    -중괄호{} 안에 작성한 코드를 함수 코드, 소스텍스트로도 부름
    -함수코드 작성은 선택
    -함수이름 규칙 : 첫문자는 반드시 영문자, $, _로 시작해야함 // 숫자,& * @ +를 첫문자로 사용 불가
    -함수이름은 함수코드를 읽지 않더라고 시맨틱(의미)를 부여하여 작명해야함
    -함수이름은 동사로 시작, 두번째 단어부터는 명사사용, 명사의 첫문자는 대문자로 사용 (CamelCase)
    -함수이름이 길게 쓰이더라도 구체적인 시맨틱을 갖는 것이 더 좋음.
    */

    function setBookTitle() {    //함수 이름은 동사로 시작하고 두번째명사는 첫문자를 대문자로 써야함 
        var title = "JS 책";        //동사+명사 형태의 동적인 모습으로 보여야함. 함수는 항상 처리하기 때문에 동적이여야함.
    };



    function book(){
        var title = "JS 책";
    };
    //function선언해서 함수 만든 형태, 함수이름 book

    var point = function(one,two) {
        var total = one + two;
        var bonus = total + 100;
    }; /* 함수를 변수에 할당한 형태, 함수이름 point
    일반적으로 파라미터가 5개이상 넘어가면 가독성이 떨어지기 때문에 다른 방법을 찾아야함.*/


    /* 
    함수는 호출되어야 실행됨 
    함수 호출하는 인자값에 들어갈수 있는것 : string, 함수이름, 컴마로 구분해서 다수작성가능
    함수는 함수이름()형태로 작성, 소괄호를 작성하지 않으면 호출 되지 않음!
    함수 선언 -> 함수호출 -> 함수코드 실행 -> 함수를 호출한 곳으로 다시 돌아감 
    */

    /* return
    -함수안에서 많이 사용함
    -return 표현식 opt;
    -표현식의 평가 결과 반환 (자신을 불러준 곳으로 결과값을 돌려줌)
    -return을 작성하지 않으면 undefined를 반환
    */

    function getPoint() {
        return 10 * 30;
    };
    var result = getPoint();
    console.log(result);

    //getPoint()함수 호출 -> return의 오른쪽 표현식 10*30을 평가 -> 평가결과 300을 반환 -> 300을 getPoint()로 리턴 -> 300을 result변수에 할당.

    function getPoint2(){
    };
    var result = getPoint2();
    console.log(typeof result);
    /*실행결과 : undefined
    return을 작성하지 않으면 값을 반환하지 않는 것이 아니라 undefined값을 반환. JS에서 undefined는 값임*/


    function geetPoint3(){
        return
        10*30;
    };


    //줄을 분리하여 표현식을 작성할 경우 
    var result3=getPoint3();
    console.log(result3);
    /*실행결과 : undefined
    자바스크립트에서는 return뒤 줄바꿈이 되면 자동으로 세미콜론을 첨부시킴
    return문에서 빈값을 return하므로 10 * 30을 수행하지 않고 undefined가 된다 */



    //실제 현직에서 쓰이는 주석사례

    /**
    *@function calculateAmount
    *1. 파라미터로 받은 수량에 단가를 곱해 금액을 계산하고 결과 값을 반환한다.
    *2. 수량과 단가의 0 체크는 함수를 호출하기 전에 하므로 체크하지 않는다. 
    *@param {Number} quantity, 수량
    *@param {Number} price, 단가
    *@return {Number} 계산 결과
    */

    function calculateAmount(quantity, price){
        //주석을 자세하게 작성하기 위해
        //함수 코드를 분리하는 경우도 있습니다. 
    }


</script>